config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  # devise_for :users
  # get '/register', to: "devise/registrations#new"


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }


  get '/users/:id', to: "users#show", as: 'user'

  resources :boards do
    resources :shots
  end
  
  resources :games


  # devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }


end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to  :board
  has_one :player, through: :board

  validates_uniqueness_of :coordinate
  
  def self.most_recent
    self.last
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
include ShotHelper

	def new
		@shot = Shot.new
	end

	def create
    p "*"*50
    p current_user
    p "*"*50
		@board = Board.find_by(player_id: enemy)
		@shot = @board.shots.create(params[:shot].permit(:coordinate))
    redirect_to game_path(@board.game.id)
	end

end

app/helpers/shot_helper.rb
module ShotHelper

  def enemy
    if current_user.id == 1
      return 2
    else
      return 1
    end
  end

end

app/views/shots/_form.html.erb
<%= form_for :shot, :url => board_shots_path(params[:id]) do |f| %>
	<% if @shot.errors.any? %>
		<div id="errors">
    	<h2><%= pluralize(@post.errors.count, "errors") %> prevented this post from saving</h2>
    	<ul>
    		<% @post.errors.full_messages.each do |msg| %>
    			<li><%= msg %></li>
    		<% end %>
    	</ul>
    </div>
  <% end %>
  <p>
  	<%= f.label :coordinate %>
  	<%= f.text_field :coordinate%>
  </p>
  <p>
  	<%= f.submit "Take shot!"%>
  </p>
<% end %>

app/views/shots/new.html.erb
<%= render "shots/form" %>