config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  # devise_for :users
  # get '/register', to: "devise/registrations#new"


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }


  get '/users/:id', to: "users#show", as: 'user'

  resources :boards do
    resources :shots
  end
  
  resources :games


  # devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to  :player, class_name: "User"
  belongs_to  :game
  has_many  :ships
  has_many  :shots
  accepts_nested_attributes_for :ships

  attr_reader :grid, :x_axis_letters, :y_axis_numbers
  after_initialize :generate_board

  def generate_board
    # Generates a board hash after the board object has been added to the database.
    @x_axis_letters = %w(a b c d e f g h i j)
    @y_axis_numbers = %w(0 1 2 3 4 5 6 7 8 9)

    @grid = {}

    @x_axis_letters.each do |x|
      @y_axis_numbers.each do |y|
        add_to_grid(x + y) # x + y will eval to: a1, b7 etc...
      end
    end
  end

  # private
  def add_to_grid(coordinate)
    # Takes in coordinate and adds them to the boards grid.
    self.grid[coordinate] = { hit?: hit?(coordinate),
                              boat?: boat?(coordinate),
                              }
  end

  def hit?(check)
    return true if hit_coordinates(check)
    false
  end

  def hit_coordinates(check)
    self.shots.find do |shot|
      shot.coordinate == check
    end
  end

  def boat?(check)
    return true if boat_coordinates(check).include?(check)
    false
  end

  def boat_coordinates(check)
    ship_coordinates = []
    self.ships.each do |ship|
      ship_coordinates << ship.all_coordinates
    end
  ship_coordinates.flatten
  end

end

app/models/game.rb
class Game < ApplicationRecord
  has_many  :boards
  has_many  :players, through: :boards
  has_many  :shots, through: :boards
  has_many  :ships, through: :boards
  belongs_to  :creator, class_name: "User"
  belongs_to  :winner, class_name: "User", optional: true

  def winner?
    return true if !Game.last.winner.nil?
    false
  end

end

app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to  :ship_type
  belongs_to  :board



  def all_coordinates
    start = self.start_point
    offset = self.ship_type.squares
    orientation = self.orientation
    counter = 1
    coordinates = [start]


    if orientation == "vertical"
      y_axis = start[0]
      until counter == offset
        y_axis = y_axis.next
        coordinates << y_axis + start[1]
        counter += 1
      end
    else
      x_axis = start[1]
      until counter == offset
        x_axis = x_axis.next
        coordinates << start[0] + x_axis
        counter += 1
      end
    end
    coordinates
  end


  # def boat?
  #   self.ships.each do |ship|
  #     start = ship.start_point
  #     offset = ship.ship_type.squares
  #     orientation = ship.orientation

  #     if orientation == "horizontal"
  #       self.grid[start][:boat?] = true
  #       coordinate = start.split("")
  #       offset.times do
  #         coordinate[1] = coordinate[1].to_i + 1
  #         self.grid[coordinate.join][:boat?] = true
  #       end

  #     end
  #   end
  # end
end

app/models/ship_type.rb
class ShipType < ApplicationRecord
  has_many  :ships
end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to  :board
  has_one :player, through: :board

  validates_uniqueness_of :coordinate
  
  def self.most_recent
    self.last
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :boards, foreign_key: :player_id
  has_many  :created_games, class_name: "Game", foreign_key: :creator_id
  has_many  :games, through: :boards, source: :game
  has_many :shots, through: :boards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/boards/boards_controller.rb
class BoardsController < ApplicationController

  def index
    p "***************************************************"

    # @board = Board.create
    # logger.info @board
  end

  def show
    @board = Board.create
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @board = Board.create
    @board.generate_board
  end

  def show
    @board = Board.find(3)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	include ShipHelper
  include BoardHelper

  def new
  	@opponent = User.find(2)
  	@game = Game.create(creator: current_user)
    @board1 = Board.create(player: current_user, game: @game)
    @board2 = Board.create(player: @opponent, game: @game)
    @ships1 = generate_ships(@board1)
    @ships2 = generate_ships(@board2)

    # we need before_action authenticate to disallow a
    # user who isn't signed in from accessing this URL
    @game = Game.new(creator: current_user)
    if @game.save
      render 'new'
    else
      redirect_to "/"
    end
  end

  def show
    @game = Game.find_by(id: params[:id])
    @player1_board = Board.where(game_id: @game.id, player_id: 1)[0]
    @player2_board = Board.where(game_id: @game.id, player_id: 2)[0]
    @shot = Shot.new
  end


	def create
    @board = Board.find_by(id: params[:board][:board_id]) 
    @board.ships.each do |ship|
      info = update_ship_on_board(params[:board][:ships], ship.id, @board)
      ship.start_point = info[:start_point]
      ship.orientation = info[:orientation]
      ship.save
    end
    redirect_to game_path(@board.game.id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
include ShotHelper

	def new
		@shot = Shot.new
	end

	def create
    p "*"*50
    p current_user
    p "*"*50
		@board = Board.find_by(player_id: enemy)
		@shot = @board.shots.create(params[:shot].permit(:coordinate))
    redirect_to game_path(@board.game.id)
	end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
  def tile_class(coordinate, board)
    info = board.grid[coordinate]
    hit = info[:hit?]
    boat = info[:boat?]

    if hit && boat
      return "strike"
    elsif hit && !boat
      return "miss"
    elsif !hit && boat
      return "boat-piece"
    else
      return "water"
    end
  end

  def update_ship_on_board(params, ship_id, board)
    params[ship_id.to_s]
  end

end

app/helpers/game_helper.rb
module GameHelper

  def current_game
    if !Game.last.winner?
      Game.last
    else
    	nil
    end
  end

  def game_in_session?
  	if Game.all.empty?
  		return false
  	elsif !Game.last.winner? 
  		return true
  	else
  		return false
	end
  end

end

app/helpers/ship_helper.rb
module ShipHelper 

	def generate_ships(board)
		ships = []
		ShipType.all.each do |type|
			ships << Ship.create(ship_type: type, board: board)
		end
		ships
	end

	# def find_orientation(start_point)

	# end

end

app/helpers/shot_helper.rb
module ShotHelper

  def enemy
    if current_user.id == 1
      return 2
    else
      return 1
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dabz</title>
    <%= csrf_meta_tags %>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>


    <!-- <p class="alert alert-success notice"><%= notice %></p>
    <p class="alert alert-success" role="alert"><%= alert %></p> -->


    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand">Battleship Online</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
            <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
          </li>
          <% if user_signed_in? %>
            <% if game_in_session? %>
              <li class="nav-item">
                <!-- may possible need to change the path -->
              <%= link_to "Current Game", current_game, class: "nav-link" %>
                <!-- <a class="nav-link" href="#">Current Game</a> -->
              </li>
            <% else %>
              <li class="nav-item">
                <!-- may possibly need to change the path -->
                <%= link_to "Create Game", new_game_path, class: "nav-link" %>
                <!-- <a class="nav-link" href="#">Create Game</a> -->
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "Profile", current_user, class: "nav-link" %>
              <!-- <a class="nav-link" href="#">Profile</a> -->
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
              <!-- <a class="nav-link" href="#">Logout</a> -->
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              <!-- <a class="nav-link" href="#">Login</a> -->
            </li>
            <li class="nav-item">
              <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
              <!-- <a class="nav-link" href="#">Signup</a> -->
            </li>
          <% end %>
          <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li> -->
        </ul>
      </div>
    </nav>


    <div class="container-fluid">
      <%= yield %>
    </div>


    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>